config/routes.rb
SentimentAnalysis::Application.routes.draw do
  resources :api_query, only: [:create]
  root to: 'static_pages#home'

end

app/controllers/api_query_controller.rb
class ApiQueryController < ApplicationController
  
  def create
    hash = get_search_result
    @result = hash['results']
    
    render 'new'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApiQueryHelper
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/api_query_helper.rb
module ApiQueryHelper
  
  def get_search_result
    keyword = params[:keyword]
    url = ''
    if params[:search_type] == 'twitter'
      url = URI.parse("http://search.twitter.com/search.json?q=#{keyword}&lang=en")
    elsif params[:search_type] == 'reddit'
      url = URI.parse("http://www.reddit.com/search.json?q=#{keyword}")
    end
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
            http.request(req) 
          }
     JSON.parse(res.body)
  end
  
  def get_sentiment(text)
    sentiment_url = URI.parse('http://text-processing.com/api/sentiment/')
    data = {'text' => text}
    JSON.parse(Net::HTTP.post_form(sentiment_url, data).body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Sentiment Analysis "
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/api_query/new.html.erb
<% provide(:title, "#{params[:search_type]} search - #{params[:keyword]}") %>
<h2>Search for <%= params[:keyword] %></h2>
<ol>
	<% @result.each do |post| %>
		<li> <%= post['text'] %> 
			<div><%= get_sentiment(post['text'])['label'] %> </div>	
		</li>
	<% end %>
</ol>

 

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		by Chris Yoon
	</small>
	<nav>
		<ul>
			<li><%= link_to "Github link", 'https://github.com/chris-yoon90/new_sentiment_analysis.git', target: "_blank" %> </li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="row-fluid">
	<%= form_tag(api_query_index_path, method: :post, class: 'form-horizontal', ) do %>
		<div class="control-group">
			<%= label_tag :keyword, "Keyword to search"%>
			<div class="input-append">
				<%= text_field_tag :keyword%>
				<%= submit_tag "Search", class: "btn" %>
			</div>
		</div>
		<div class="control-group">	
			<%= label_tag :search_type, 'Twitter', class: "radio inline"%>
			<%= radio_button_tag :search_type, 'twitter', true%>
			
			<%= label_tag :search_type, 'Reddit', class: "radio inline"%>
			<%= radio_button_tag :search_type, 'reddit' %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<%= yield %>
	
	<%= render 'layouts/footer' %>

	<%= debug(params) if Rails.env.development? %>
	
</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>